language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libxslt-dev
install:
  - export CPPFLAGS="-O0"
  - pip install -e .
  - pip install -r requirements_test.txt DJANGO==$DJANGO
env:
  - DJANGO=1.4.5
  - DJANGO=1.5.1
  - DB=postgres
script:
  - make test